from random import sample

#l = ['PAVINESH J', 'PRASANNA KUMAR R', 'SIVASANKAR E', 'JAYASHREE G', 'POOJA V', 'SUHALI PREETHAM B', 'ARJUN KUMAR', 'KISHOREKUMAR B S', 'PARTHA SARATHY T', 'INFANT RUBAN SURESH S A', 'JAYAPRAKASH S', 'VIJAYA REGAN G V', 'DIVYA E', 'JAYA BHARATHI J', 'MADHUMITHA K', 'KAVIYA CHELLI S', 'SIVASANKARI G', 'HARINI SRII R', 'ROSHAN ', 'SANCHANA SUTHARSHINI T', 'VIGNESHARA M H', 'RIDWAN', 'RITHIES ATHULYA A G', 'LOKESH ILANGOVAN', 'KAVIYAA M K', 'OVIYAH M K', 'POOJYATHA VENKITESH', 'MAGESHWARI S', 'MONISH A', 'PREETHI K', 'GEETHA PRIYA S', 'SATHYA PRIYA M', 'SWETHA CHANDER E', 'RAJARAJESWARI S K', 'ARJUN KUMAR', 'VETRIMANI A U', 'BARANI RANJAN S', 'GOKUL R']
l = ["a","b","c","d"]
#x = random.shuffle(l)
print (sample(l,len(l)))